force-app/main/default/objects/EBEvent__c/EBEvent__c.object-meta.xml
<CustomObject>
    <description
  >Object contains records from Eventbrite event details. Records are populated via API calls.</description>
    <label>Eventbrite Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventbrite Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EBEvent__c/fields/capacity__c.field-meta.xml
<CustomField>
    <fullName>capacity__c</fullName>
    <description
  >Maximum number of tickets for the Event that can be sold to Attendees. The total capacity is calculated by the sum of the quantity_total of the Ticket Class.</description>
    <inlineHelpText
  >Maximum number of tickets for the Event that can be sold to Attendees. The total capacity is calculated by the sum of the quantity_total of the Ticket Class.</inlineHelpText>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/capacity_is_custom__c.field-meta.xml
<CustomField>
    <fullName>capacity_is_custom__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >true = Use custom capacity value to specify the maximum number of Attendees for the Event. False = Calculate the maximum number of Attendees for the Event from the total of all Ticket Class capacities.</description>
    <inlineHelpText
  >true = Use custom capacity value to specify the maximum number of Attendees for the Event. False = Calculate the maximum number of Attendees for the Event from the total of all Ticket Class capacities.</inlineHelpText>
    <label>Custom Capacity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/changed__c.field-meta.xml
<CustomField>
    <fullName>changed__c</fullName>
    <description
  >Date and time of most recent changes to the Event.</description>
    <inlineHelpText
  >Date and time of most recent changes to the Event.</inlineHelpText>
    <label>Changed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/created__c.field-meta.xml
<CustomField>
    <fullName>created__c</fullName>
    <description>Event creation date and time.</description>
    <inlineHelpText>Event creation date and time.</inlineHelpText>
    <label>Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/eventend__c.field-meta.xml
<CustomField>
    <fullName>eventend__c</fullName>
    <description>Event end date and time.</description>
    <inlineHelpText>Event end date and time.</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/eventid__c.field-meta.xml
<CustomField>
    <fullName>eventid__c</fullName>
    <description>Eventbrite Event Identifier</description>
    <inlineHelpText>Eventbrite Event Identifier</inlineHelpText>
    <label>Event Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/eventstart__c.field-meta.xml
<CustomField>
    <fullName>eventstart__c</fullName>
    <description>Event start date and time.</description>
    <inlineHelpText>Event start date and time.</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/listed__c.field-meta.xml
<CustomField>
    <fullName>listed__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >true = Allows the Event to be publicly searchable on the Eventbrite website.</description>
    <inlineHelpText
  >true = Allows the Event to be publicly searchable on the Eventbrite website.</inlineHelpText>
    <label>Listed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/organization_id__c.field-meta.xml
<CustomField>
    <fullName>organization_id__c</fullName>
    <description>Event is owned by this Organization.</description>
    <inlineHelpText>Event is owned by this Organization.</inlineHelpText>
    <label>Organization Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/published__c.field-meta.xml
<CustomField>
    <fullName>published__c</fullName>
    <description>Event publication date and time.</description>
    <inlineHelpText>Event publication date and time.</inlineHelpText>
    <label>Published</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <description
  >Event status. Can be draft, live, started, ended, completed and canceled.</description>
    <inlineHelpText
  >Event status. Can be draft, live, started, ended, completed and canceled.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
            </value>
            <value>
                <fullName>live</fullName>
            </value>
            <value>
                <fullName>started</fullName>
            </value>
            <value>
                <fullName>ended</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/summary__c.field-meta.xml
<CustomField>
    <fullName>summary__c</fullName>
    <description
  >Event summary. Short summary describing the event and its purpose.</description>
    <inlineHelpText
  >Event summary. Short summary describing the event and its purpose.</inlineHelpText>
    <label>Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <description
  >URL of the Event&apos;s Listing page on eventbrite.com.</description>
    <inlineHelpText
  >URL of the Event&apos;s Listing page on eventbrite.com.</inlineHelpText>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/EBEventsCallout.cls
public with sharing class EBEventsCallout {
  @future(callout=true)
  public static void getEvents(String settings) {
    EBSchema.EBEventsList eventslist = EBEvents.getEvents(settings);
    List<EBEvent__c> newevents = new List<EBEvent__c>();
    if (eventslist.events != null) {
      for (EBSchema.EBEvents evt : eventslist?.events) {
        EBEvent__c newevt = new EBEvent__c();
        newevt.Name = evt?.eventname?.text;
        newevt.eventid__c = evt?.id;
        newevt.url__c = evt?.url;
        newevt.eventstart__c = evt?.eventstart?.local;
        newevt.eventend__c = evt?.eventend?.local;
        newevt.organization_id__c = evt?.organization_id;
        newevt.created__c = evt?.created;
        newevt.changed__c = evt?.changed;
        newevt.published__c = evt?.published;
        newevt.capacity__c = evt?.capacity;
        newevt.capacity_is_custom__c = evt?.capacity_is_custom;
        newevt.status__c = evt?.status;
        newevt.listed__c = evt?.listed;
        newevt.summary__c = evt?.summary;
        newevents.add(newevt);
      }
    }
    try {
      upsert newevents eventid__c;
    } catch (DmlException e) {
      System.debug(e.getMessage());
    }
  }

  public class EBEventsRequest {
    @InvocableVariable(
      label='Eventbrite Settings'
      description='Developer API Name'
      required=true
    )
    public String settings;
  }

  @InvocableMethod(label='Get Eventbrite Events')
  public static void getEventbriteEvents(List<EBEventsRequest> inputParams) {
    for (EBEventsRequest p : inputParams) {
      getEvents(p.settings);
    }
  }
}