force-app/main/default/objects/EBAttendee__c/EBAttendee__c.object-meta.xml
<CustomObject>
    <label>Eventbrite Attendee</label>
    <nameField>
        <label>Attendee Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventbrite Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EBAttendee__c/fields/EBEvent__c.field-meta.xml
<CustomField>
    <fullName>EBEvent__c</fullName>
    <description>Eventbrite Event</description>
    <inlineHelpText>Eventbrite Event</inlineHelpText>
    <label>Eventbrite Event</label>
    <referenceTo>EBEvent__c</referenceTo>
    <relationshipLabel>Eventbrite Attendees</relationshipLabel>
    <relationshipName>Eventbrite_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/EBEvent__c.object-meta.xml
<CustomObject>
    <description
  >Object contains records from Eventbrite event details. Records are populated via API calls.</description>
    <label>Eventbrite Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventbrite Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EBEvent__c/fields/eventid__c.field-meta.xml
<CustomField>
    <fullName>eventid__c</fullName>
    <description>Eventbrite Event Identifier</description>
    <inlineHelpText>Eventbrite Event Identifier</inlineHelpText>
    <label>Event Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBEvent__c/fields/organization_id__c.field-meta.xml
<CustomField>
    <fullName>organization_id__c</fullName>
    <description>Event is owned by this Organization.</description>
    <inlineHelpText>Event is owned by this Organization.</inlineHelpText>
    <label>Organization Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eventbrite_Setting__mdt/Eventbrite_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Eventbrite Setting</label>
    <pluralLabel>Eventbrite Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Eventbrite_Setting__mdt/fields/Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Id__c</fullName>
    <label>Organization Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eventbrite_Setting__mdt/fields/Private_Token__c.field-meta.xml
<CustomField>
    <fullName>Private_Token__c</fullName>
    <label>Private Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_EBAttendeesCallout.cls
@IsTest
private class Test_EBAttendeesCallout {
  @IsTest
  private static void testGetAttendeesNoData() {
    Test.setMock(HttpCalloutMock.class, new Test_EBAttendeesCalloutMock());
    String settingsJSON = '[' + '\n';
    settingsJSON += '{' + '\n';
    settingsJSON += '"DeveloperName": "EBSettings",' + '\n';
    settingsJSON += '"MasterLabel": "EBSettings",' + '\n';
    settingsJSON += '"Private_Token__c": "your_private_token",' + '\n';
    settingsJSON += '"Organization_Id__c": "your_organization_id"' + '\n';
    settingsJSON += '}' + '\n';
    settingsJSON += ']';
    String query = 'SELECT Private_Token__c, Organization_Id__c FROM Eventbrite_Setting__mdt WHERE DeveloperName = \'EBSettings\'';
    Test_EBMetadata.setMetadata(
      query,
      (List<Eventbrite_Setting__mdt>) JSON.deserialize(
        settingsJSON,
        List<Eventbrite_Setting__mdt>.class
      )
    );
    Test.startTest();
    List<EBAttendeesCallout.EBAttendeesRequest> inputParams = new List<EBAttendeesCallout.EBAttendeesRequest>();
    EBAttendeesCallout.EBAttendeesRequest p1 = new EBAttendeesCallout.EBAttendeesRequest();
    p1.settings = 'EBSettings';
    p1.eventId = 'event_id';
    inputParams.add(p1);
    EBAttendeesCallout.getEventbriteAttendees(inputParams);
    Test.stopTest();
    // runs callout and check results
    List<EBAttendee__c> allattendees = [SELECT Id FROM EBAttendee__c];
    System.assertEquals(allattendees.size(), 0, 'Expected record size is 0.');
  }

  @IsTest
  private static void testGetAttendeesWithData() {
    Test.setMock(
      HttpCalloutMock.class,
      new Test_EBAttendeesCalloutMockWithData()
    );
    String settingsJSON = '[' + '\n';
    settingsJSON += '{' + '\n';
    settingsJSON += '"DeveloperName": "EBSettings",' + '\n';
    settingsJSON += '"MasterLabel": "EBSettings",' + '\n';
    settingsJSON += '"Private_Token__c": "your_private_token",' + '\n';
    settingsJSON += '"Organization_Id__c": "your_organization_id"' + '\n';
    settingsJSON += '}' + '\n';
    settingsJSON += ']';
    String query = 'SELECT Private_Token__c, Organization_Id__c FROM Eventbrite_Setting__mdt WHERE DeveloperName = \'EBSettings\'';
    Test_EBMetadata.setMetadata(
      query,
      (List<Eventbrite_Setting__mdt>) JSON.deserialize(
        settingsJSON,
        List<Eventbrite_Setting__mdt>.class
      )
    );
    Test.startTest();
    List<EBAttendeesCallout.EBAttendeesRequest> inputParams = new List<EBAttendeesCallout.EBAttendeesRequest>();
    EBAttendeesCallout.EBAttendeesRequest p1 = new EBAttendeesCallout.EBAttendeesRequest();
    p1.settings = 'EBSettings';
    p1.eventId = 'event_id';
    inputParams.add(p1);
    EBEvent__c evt = new EBEvent__c();
    evt.eventid__c = 'event_id';
    insert evt;
    EBAttendeesCallout.getEventbriteAttendees(inputParams);
    Test.stopTest();
    // runs callout and check results
    List<EBAttendee__c> allattendees = [SELECT Id FROM EBAttendee__c];
    System.assertEquals(allattendees.size(), 1, 'Expected record size is 1.');
  }
}